# Generated by Django 4.0.6 on 2022-07-29 03:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0002_product_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
