# Generated by Django 4.0.6 on 2022-07-29 04:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
