# Generated by Django 4.0.6 on 2022-07-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
