# Generated by Django 4.0.6 on 2022-07-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0008_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
